apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./mnt/data"