version: "3.8"
services:
  sportsevents-db:
    image: "postgres"
    mem_limit: 128m
    environment:
      POSTGRES_USER: sportsevents
      POSTGRES_PASSWORD: sportsevents
      POSTGRES_DB: sportsevents
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sportsevents"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - 5433:5432
    volumes:
      - "./scripts/sql/create.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/sql/insert.sql:/docker-entrypoint-initdb.d/2.sql"

  keycloak:
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: superSecret
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    depends_on:
      - keycloak-db
    ports:
      - 8081:8080

  keycloak-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  monitoring:
    image: "prom/prometheus"
    container_name: "super-visor"
    ports:
      - 9090:9090
    volumes:
      - "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
