{
 "title": "Request timers dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average request time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timed_get_event_request_seconds_sum{application=\"$application\", instance=\"$instance\"} / \ntimed_get_event_request_seconds_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "get_event"
    },
    {
     "expr": "timed_get_events_request_seconds_sum{application=\"$application\", instance=\"$instance\"} / \ntimed_get_events_request_seconds_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "get_events"
    },
    {
     "expr": "timed_add_player_request_seconds_sum{application=\"$application\", instance=\"$instance\"} /\ntimed_add_player_request_seconds_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "add_player"
    },
    {
     "expr": "timed_remove_player_request_seconds_sum{application=\"$application\", instance=\"$instance\"} /\ntimed_remove_player_request_seconds_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "remove_player"
    },
    {
     "expr": "timed_create_event_request_seconds_sum{application=\"$application\", instance=\"$instance\"} /\ntimed_create_event_request_seconds_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "create_event"
    },
    {
     "expr": "timed_close_event_request_seconds_sum{application=\"$application\", instance=\"$instance\"} /\ntimed_close_event_request_seconds_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "close_event"
    },
    {
     "expr": "timed_get_leaderboard_request_seconds_sum{application=\"$application\", instance=\"$instance\"}/\ntimed_get_leaderboard_request_seconds_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "get_leaderboard"
    }
   ]
  },
  {
   "title": "Max request time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(timed_add_player_request_seconds_max{application=\"$application\", instance=\"$instance\"})[1d:1m])",
     "legendFormat": "add_player"
    },
    {
     "expr": "max_over_time(sum(timed_close_event_request_seconds_max{application=\"$application\", instance=\"$instance\"})[1d:1m])",
     "legendFormat": "close_event"
    },
    {
     "expr": "max_over_time(sum(timed_create_event_request_seconds_max{application=\"$application\", instance=\"$instance\"})[1d:1m])",
     "legendFormat": "create_event"
    },
    {
     "expr": "max_over_time(sum(timed_get_event_request_seconds_max{application=\"$application\", instance=\"$instance\"})[1d:1m])",
     "legendFormat": "get_event"
    },
    {
     "expr": "max_over_time(sum(timed_get_events_request_seconds_max{application=\"$application\", instance=\"$instance\"})[1d:1m])",
     "legendFormat": "get_events"
    },
    {
     "expr": "max_over_time(sum(timed_get_leaderboard_request_seconds_max{application=\"$application\", instance=\"$instance\"})[1d:1m])",
     "legendFormat": "get_leaderboard"
    },
    {
     "expr": "max_over_time(sum(timed_remove_player_request_seconds_max{application=\"$application\", instance=\"$instance\"})[1d:1m])",
     "legendFormat": "remove_player"
    }
   ]
  },
  {
   "title": "Total requests counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "rate(timed_create_event_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "create_event"
    },
    {
     "expr": "rate(timed_get_event_request_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "get_event"
    },
    {
     "expr": "rate(timed_get_events_request_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "get_events"
    },
    {
     "expr": "rate(timed_get_leaderboard_request_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "get_leaderboard"
    },
    {
     "expr": "rate(timed_add_player_request_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "add_player"
    },
    {
     "expr": "rate(timed_remove_player_request_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "remove_palyer"
    },
    {
     "expr": "rate(timed_close_event_request_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "close_event"
    },
    {
     "expr": "rate(timed_delete_event_request_seconds_count{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "delete_event"
    }
   ]
  }
 ]
}