version: "3.8"
services:
  sportsevents-quarkus-app:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: sportsevents-springboot:1.0.0-SNAPSHOT
    ports:
      - "8089:8089"
    # depends_on:
    #   - sportsevents-spring-db
    #   - keycloak
    #   - monitoring
    environment:
      KC_HOST: keycloak
      KC_PORT: 8080
      DB_HOST: sportsevents-spring-db
      DB_PORT: 5432
networks: 
  default:
      name: app-network