apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ping-quarkus-jvm
  name: ping-quarkus-jvm
spec:
  containers:
  - args:
    - sh
    - -c
    - while(true) do echo "\n Trying to connect to quarkus-jvm... "; time wget -T1 -O- http://quarkus-jvm-service:8082/test-kube ; sleep 0.1; done
    image: busybox
    name: ping-quarkus-jvm
    resources:
      limits:
        memory: 1G
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}