apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ping-springboot
  name: ping-springboot
spec:
  containers:
  - args:
    - sh
    - -c
    - while(true) do echo "\n Trying to connect to springboot... "; time wget -T1 -O- http://springboot-service:8089/test-kube ; sleep 0.1; done
    image: busybox
    name: ping-springboot
    resources:
      limits:
        memory: 1G
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}