apiVersion: v1
kind: Service
metadata:
  name: springboot-postgres-service
spec:
  selector:
    app: springboot-postgres-deployment
  ports:
    - protocol: TCP
      port: 5434
      targetPort: 5434